### ISSUE TITLE
What happened to Forivy?

### ISSUE THREAD

**Issue by hdmitweaker** [dadav/pwnagotchi-custom-plugins#1]
I didn't see your contact info on your Github page. Do you know what happened to Forivy? It suddenly vanished from Github and Ankiweb.

**Comment by dadav** [comment]
I closed the project.

**Comment by hdmitweaker** [comment]
Why? It was one of the most amazing add-ons for Anki. It transformed adding audio for cards from one of the most difficult tasks to an absolute breeze. Could you at least bring back the repository so that even if you don't wish to develop it anymore, then somebody else can?
